# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-12 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcuts',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
