# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-12 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20190112_1859'),
        ('user', '0002_registermodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(default='incart', max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.RegisterModel')),
                ('purhased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.Prodcuts')),
            ],
        ),
    ]
