# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-13 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_reviewmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visual_Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateogory', models.CharField(max_length=200)),
                ('vals', models.IntegerField()),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.RegisterModel')),
            ],
        ),
    ]
