# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-13 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20190112_1859'),
        ('user', '0005_visual_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visual_sequence',
            name='proid',
        ),
        migrations.AddField(
            model_name='visual_sequence',
            name='prosid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admins.Prodcuts'),
            preserve_default=False,
        ),
    ]
