# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-13 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20190112_1859'),
        ('user', '0006_auto_20190113_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visual_Sequences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateogory', models.CharField(max_length=200)),
                ('vals', models.IntegerField()),
                ('prosid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.Prodcuts')),
            ],
        ),
    ]
