# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-13 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_visual_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='sentiment',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
