# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-13 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_reviewmodel_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cate',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='proname',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
